name: 2-Create-Log-Analytics-Workspace
on: workflow_dispatch

env:
  RESOURCE_GROUP: "ucorp-logging1-rg"

jobs:
  build:
    name: 2-Create-Log-Analytics-Workspace
    runs-on: windows-latest
    steps:
    # Authentication: log on to Azure with the AZURE_CREDENTIALS secret
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    
    # Azure PowerShell: Run inline script    
    - name: Run Azure PowerShell script (inline)
      uses: azure/powershell@v1
      with:
        inlineScript: |
          # Read the environment variables in PowerShell
          [string]$ResourceGroup = [System.Environment]::GetEnvironmentVariable('RESOURCE_GROUP')

          $Tags = @{"Environment"="WVD Production"}
          $Location = "westeurope"
          $WorkspaceName = "ucorp-wvdlog-law"

          # Create the resource group if needed
          try {
              Get-AzResourceGroup -Name $ResourceGroup -ErrorAction Stop
          } catch {
              New-AzResourceGroup -Name $ResourceGroup -Location $Location -Tag $Tags
          }
          
          # Create the workspace
          New-AzOperationalInsightsWorkspace -Location $Location -Name $WorkspaceName -Sku Standard -ResourceGroupName $ResourceGroup -Tag $Tags -Verbose

          # List of solutions to enable
          $Solutions = "Updates", "AntiMalware", "LogManagement", "AzureResources", "LogicAppsManagement", "VMInsights"

          # Saved Searches to import
          # $ExportedSearches = @"
          # [
          #    {
          #        "Category":  "My Saved Searches",
          #        "DisplayName":  "WAD Events (All)",
          #        "Query":  "Type=Event SourceSystem:AzureStorage ",
          #        "Version":  1
          #    },
          #    {
          #        "Category":  "My Saved Searches",
          #        "DisplayName":  "Current Disk Queue Length",
          #        "Query":  "Perf | where ObjectName == "LogicalDisk" and CounterName == "Current Disk Queue Length" and InstanceName == "C:"",
          #        "Version":  1
          #    }
          # ]
          # "@ | ConvertFrom-Json

          # Custom Log to collect
          # $CustomLog = @"
          # {}
          # "@

          # Add solutions
          foreach ($solution in $Solutions) {
              Set-AzOperationalInsightsIntelligencePack -ResourceGroupName $ResourceGroup -WorkspaceName $WorkspaceName -IntelligencePackName $solution -Enabled $true
          }

          # Import Saved Searches
          #foreach ($search in $ExportedSearches) {
          #    $id = $search.Category + "|" + $search.DisplayName
          #    New-AzOperationalInsightsSavedSearch -ResourceGroupName $ResourceGroup -WorkspaceName $WorkspaceName -SavedSearchId $id -DisplayName $search.DisplayName -Category $search.Category -Query $search.Query -Version $search.Version
          }

          # Windows Event
          New-AzOperationalInsightsWindowsEventDataSource -ResourceGroupName $ResourceGroup -WorkspaceName $WorkspaceName -EventLogName "Microsoft-Windows-Windows Defender/Operational" -CollectErrors -CollectWarnings -Name "Windows Defender"

          # Custom Logs
          # New-AzOperationalInsightsCustomLogDataSource -ResourceGroupName $ResourceGroup -WorkspaceName $WorkspaceName -CustomLogRawJson "$CustomLog" -Name "Example Custom Log Collection"

        azPSVersion: 'latest'
