name: 4-Add-WVD-Session-Host
on: workflow_dispatch

jobs:
  build:
    name: 4-Add-WVD-Session-Host
    runs-on: windows-latest
    steps:
    # Authentication: log on to Azure with the AZURE_CREDENTIALS secret
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    
    # Azure PowerShell: Run inline script    
    - name: Run Azure PowerShell script (inline)
      uses: azure/powershell@v1
      with:
        inlineScript: |
          # Read the environment variables in PowerShell
          $Tags = @{"Environment"="WVD Production"}
          $CustomerPrefix = "Ucorp"
          $HostPoolName = "Ucorp-WVD-Pool" 
          $Sig = "ucorpwvdsig"
          $SigImageDefName = "Ucorp-WVD-Image"
          $vmSize = "Standard_D4s_v3"
          $VaultName = "Ucorp-WVD-KV"
          $NumberOfInstances = 1
          
          # Retrieve the given Host Pool information
          try 
          {
              $hostPool = Get-AzWvdHostPool -SubscriptionId ${{secrets.AZURE_SUBSCRIPTIONID}} | Where {$_.Name -eq $HostPoolName}
          }
          catch 
          {
              Write-Error ("A [" + $_.Exception.GetType().FullName + "] ERROR occurred. " + $_.Exception.Message)
              Break
          }
          If ($hostPool.Count -gt 0)
          {
            $hostpoolRG = $hostPool.Id.Split("/")[4]
            $hostpoolName = $hostPool.Id.Split("/")[-1]
            # Retrieve the current Session Host information
            try
            {
              $sessionHost = Get-AzWvdSessionHost -HostPoolName $($hostpool.Name) -ResourceGroupName $($hostpoolRG) | Select-Object -Last 1
            }
            catch
            {
              Write-Error ("A [" + $_.Exception.GetType().FullName + "] ERROR occurred. " + $_.Exception.Message)
              Break
            }

            # Determine new Session Host number
            $vmTemplate = ($hostPool.VMTemplate | ConvertFrom-Json)
            $sessionHostNumber = $($SessionHost.Name.Split("/")[1].Split(".")[0] -replace "$($vmTemplate.namePrefix)-")
            if($sessionHostNumber -eq $null)
            {
              $vmInitialNumber = 0
            }
            Else {
              $lastSessionHostNumber = [int]($sessionHostNumber)
              $vmInitialNumber = $lastSessionHostNumber + $NumberOfInstances
            }

            $vmCustomImageSourceId = "/subscriptions/${{secrets.AZURE_SUBSCRIPTIONID}}/resourceGroups/$CustomerPrefix-WVD-RG/providers/Microsoft.Compute/galleries/$Sig/images/$SigImageDefName";

            # Retrieve sensitive information from KeyVault
            $secureAdminPassword = (Get-AzKeyVaultSecret -VaultName $VaultName -Name domainadminpassword).SecretValue
            $secureDomainAdminUser = (Get-AzKeyVaultSecret -VaultName $VaultName -Name domainadminuser).SecretValue
            $secureDomainName = (Get-AzKeyVaultSecret -VaultName $VaultName -Name domainname).SecretValue
            $secureOuPath = (Get-AzKeyVaultSecret -VaultName $VaultName -Name domainoupath).SecretValue
            
            # Convert KeyVault SecureString to Plaintext
            $domainAdminUser = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureDomainAdminUser)))
            $domainName = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureDomainName)))
            $ouPath = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureOuPath)))
                      
            # Retrieve the vNet and subnet information of the VM
            $sessionHostName = $($sessionHost.Name.Split("/")[1].Split(".")[0])
            $sessionHostRG = (Get-AzVM -Name $sessionHostName).ResourceGroupName
            $sessionHostLocation = (Get-AzVM -Name $sessionHostName).Location
            $vnetInfo = (Get-AzNetworkInterface -ResourceGroupName $sessionHostRG | where {$_.Name -like "$($sessionHostName)*"}).IpConfigurations[0].Subnet.id.Split("/")[8]
            $subnetInfo = (Get-AzNetworkInterface -ResourceGroupName $sessionHostRG | where {$_.Name -like "$($sessionHostName)*"}).IpConfigurations[0].Subnet.id.Split("/")[10]
            $vnetrgInfo = (Get-AzNetworkInterface -ResourceGroupName $sessionHostRG | where {$_.Name -like "$($sessionHostName)*"}).IpConfigurations[0].Subnet.id.Split("/")[4]
            
            # Retrieve Hostpool token
            $registrationInfo = Get-AzWvdRegistrationInfo -SubscriptionId ${{secrets.AZURE_SUBSCRIPTIONID}} -ResourceGroupName $($hostpoolRG) -HostPoolName $($hostpoolName)
            
            if ($($registrationInfo.ExpirationTime) -le $((Get-Date).ToUniversalTime().ToString('MM/dd/yyyy HH:mm:ss')) -and $(!([string]::IsNullOrEmpty($registrationInfo.ExpirationTime))))
            {
              $hostpoolToken = $registrationInfo.Token
            }
            else
            {
              $hostpoolToken = $((New-AzWvdRegistrationInfo -ResourceGroupName $hostpoolRG -HostPoolName $HostPoolName -ExpirationTime $((Get-Date).ToUniversalTime().AddDays(1).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))).Token)
            }
            ## Create a Template Parameter Object (hashtable)
            $objTemplateParameter = @{
              "hostpoolName" = $HostPoolName;
              "hostpoolToken" = $hostpoolToken;
              "hostpoolResourceGroup" = $($hostPool.Id.Split("/")[4]);
              "hostpoolProperties" = @{};
              "hostpoolLocation" = $($hostPool.Location);
              "createAvailabilitySet" = $false;
              "vmInitialNumber" = $vmInitialNumber;
              "vmResourceGroup" = $($sessionHostRG);
              "vmLocation" = $($sessionHostLocation);
              "vmSize" = $vmSize;
              "vmNumberOfInstances" = $NumberOfInstances;
              "vmNamePrefix" = $($vmTemplate.namePrefix);
              "vmImageType" = $($vmTemplate.imageType);
              "vmImageVhdUri" = [string]$($vmTemplate.imageUri);
              "vmDiskType" = $($vmTemplate.osDiskType);
              "vmUseManagedDisks" = $($vmTemplate.useManagedDisks);
              "existingVnetName" = $($vnetInfo);
              "existingSubnetName" = $($subnetInfo);
              "virtualNetworkResourceGroupName" = $($vnetrgInfo);
              "createNetworkSecurityGroup" = $false;
              "virtualMachineTags" = $Tags;
              "apiVersion" = "2019-12-10-preview";
              "administratorAccountUsername" = "$($domainAdminUser)";
              "domain"="$($domainName)";
              "ouPath"="$($ouPath)";
              "aadJoin" = $false;
              "intune" = $false;
            }
            
            # Add additional parameters, based on image type
            If ($vmTemplate.imageType -eq "Gallery")
            {
                # Add the Gallery image information
                $objTemplateParameter.Add("vmGalleryImageOffer",$($vmTemplate.galleryImageOffer))
                $objTemplateParameter.Add("vmGalleryImagePublisher",$($vmTemplate.galleryImagePublisher))
                $objTemplateParameter.Add("vmGalleryImageSKU",$($vmTemplate.galleryImageSKU))
            }
            If ($vmTemplate.imageType -eq "CustomImage")
            {
                # Add the Gallery image information
                $objTemplateParameter.Add("vmCustomImageSourceId",$($vmCustomImageSourceId))
            }

            ## Show objTemplateParameter
            #$objTemplateParameter
            
            # Temp location for the ARM template that will be used by this script (discarded when runbook is finished)
            $jsonARMTemplateFile = [string]($env:TEMP + "\4-ARM-Add-WVD-Session-Host.json")
            
            # Storage location for custom ARM template
            $templateUrl="https://raw.githubusercontent.com/iuenk/WVD/main/ARMTemplates/4-ARM-Add-WVD-Session-Host.json"
            
            # Retrieve the template file and save it in a temp file location
            Invoke-WebRequest -Uri $templateUrl -OutFile $jsonARMTemplateFile -UseBasicParsing
            
            # ARM Template file
            ## Add SessionHosts to existing WVD Hostpool, based on ARM Template
            New-AzResourceGroupDeployment -ResourceGroupName $hostpoolRG -TemplateFile $jsonARMTemplateFile -TemplateParameterObject $objTemplateParameter -administratorAccountPassword $secureAdminPassword -Verbose
          }

        azPSVersion: 'latest'
