name: 6-Create-WVD-Scaling
on: workflow_dispatch

env:
  STORAGE_ACCOUNT: "ucorpwvdstd"
  RESOURCE_GROUP: "ucorp-wvd1-rg"

jobs:
  build:
    name: 6-Create-WVD-Scaling
    runs-on: windows-latest
    steps:
    # Authentication: log on to Azure with the AZURE_CREDENTIALS secret
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    
    # Azure PowerShell: Run inline script    
    - name: Run Azure PowerShell script (inline)
      uses: azure/powershell@v1
      with:
        inlineScript: |
          # Read the environment variables in PowerShell
          [string]$storageAccountName = [System.Environment]::GetEnvironmentVariable('STORAGE_ACCOUNT')
          [string]$ResourceGroup = [System.Environment]::GetEnvironmentVariable('RESOURCE_GROUP')

          $Tags = @{"Environment"="WVD Production"}
          $FunctionFilePath = "https://github.com/iuenk/WVD/blob/main/PSScripts/run.ps1"

          # Create the resource group if needed
          try {
              Get-AzResourceGroup -Name $ResourceGroup -ErrorAction Stop
          } catch {
              New-AzResourceGroup -Name $ResourceGroup -Location "westeurope" -Tag $Tags
          }

          # Read the contents of the function file and assemble deployment parameters
          $functionFileContents = [System.IO.File]::ReadAllText($FunctionFilePath)
          $objTemplateParameter = @{
            "functionsAppName" = "ucorpscaling";
            "FunctionName" = "ucorpwvdscalingtimer";
            "functionsStorageAccountName" = "ucorpwvdstd"
            }
          $templateParameters.Add("functionFile", $functionFileContents)

          # Temp location for the ARM template that will be used by this script (discarded when runbook is finished)
          $jsonARMTemplateFile = [string]($env:TEMP + "\6-ARM-Create-WVD-Scaling.json")
              
          # storage location for custom ARM template
          $templateUrl="https://raw.githubusercontent.com/iuenk/WVD/main/ARMTemplates/6-ARM-Create-WVD-Scaling.json"

          # Retrieve the template file and save it in a temp file location
          Invoke-WebRequest -Uri $templateUrl -OutFile $jsonARMTemplateFile -UseBasicParsing

          # ARM Template file
          ## Add SessionHosts to existing WVD Hostpool, based on ARM Template
          New-AzResourceGroupDeployment -ResourceGroupName $ResourceGroup -TemplateFile $jsonARMTemplateFile -TemplateParameterObject $objTemplateParameter -Tag $Tags -Verbose

        azPSVersion: 'latest'